### ISSUE TITLE
An update?

### ISSUE THREAD

**Issue by paaljoachim** [acclectic/media-organizer#20]
Hey

I am going through various Media Library folder plugins and your Acclectic Media Organizer plugin stood out.
It does not have any settings page, and it keeps it nice and clean inside the left sidebar of the Media Library.

Do you have plans to update the plugin? As it shows that it is being updated. Even a minor update shows that the plugin has not been forgotten. Thanks!

Ps
I am creating a tutorial and hope to highlight your plugin.

**Comment by acclectic** [comment]
Hello! Thank you for the comment!

Yes, this plugin is still under active development so we do plan to update it. We agree that we should push more minor updates to show it's still active. Thanks for the suggestion! We'll do some more testing with the latest version WordPress and update it accordingly.

**Comment by paaljoachim** [comment]
Great to hear!

Updating every 3-4 months even minor helps the public perception that the plugin is being maintained/developed/looked after and not forgotten by the developer.

I might actually start using the plugin and see how it works now that I know that the plugin is not forgotten.

**Comment by acclectic** [comment]
Thank you again for your comment. Much appreciated. We just pushed a release v1.4 to verify functionality with Wordpress 6.0 and updated the theme color.
