### ISSUE TITLE
Adjusting the grey colors.

### ISSUE THREAD

**Issue by paaljoachim** [acclectic/media-organizer#21]
They color grey is usually associated with controls that are deactivated.

![Screenshot 2022-09-13 at 11 51 01](https://user-images.githubusercontent.com/5323259/189870954-86341de5-b383-4aae-95f1-005afb665a70.jpg)

It would be helpful to change this.

I experimented with the dev console CSS area.

Having a lighter color helps. It feels more active.
![Screenshot 2022-09-13 at 12 01 33](https://user-images.githubusercontent.com/5323259/189873194-0a028224-40d8-444a-923a-073732df9c65.jpg)

The blue button becomes too active and stands out too much, but it gives an idea.
I was thinking of WordPress default colors when exploring the above.

**Comment by acclectic** [comment]
Thank you for the suggestion! Yes, the grey also seemed a little drab so we'll update it with the next release.

**Comment by paaljoachim** [comment]
Sounds great!

**Comment by acclectic** [comment]
Thank you again for the suggestion. Updated in v1.4, just released.
