### ISSUE TITLE
Clicking various created folders shows the same as in All items and Unassigned items.

### ISSUE THREAD

**Issue by paaljoachim** [acclectic/media-organizer#30]
Example.

Unassigned items is selected.

![Screenshot 2022-10-14 at 11 59 21](https://user-images.githubusercontent.com/5323259/195820162-8b1cfd52-ed3a-4e46-be0b-060350b32996.jpg)

Los Angeles Post images selected.
![Screenshot 2022-10-14 at 11 59 35](https://user-images.githubusercontent.com/5323259/195820213-84579df7-c967-4982-96f1-910596336754.jpg)

It feels like the plugin is just not working correctly. As all the folders show the same.

**Comment by acclectic** [comment]
Hi. Thanks for reporting this. We are not able to reproduce this. If possible, would you mind sending us your console logs? (Shift-Ctrl-C then Console if you're using Chrome).

Also, does the behavior change is you move one of the images to a folder?

**Comment by paaljoachim** [comment]
I will begin by deleting some of the folders I have added.
Then starting over adding folders.
Images
-- Modeling
-- Other images

Dragging images into the two subfolders. 
Now I can see the difference.

![Screenshot 2022-10-15 at 22 27 28](https://user-images.githubusercontent.com/5323259/196006312-746a0b8b-b0b4-4a2a-a895-f19761bc91de.jpg)

It might have to do with dragging folders around. It seemed to stay the same.
I will add some additional comments to this issue: https://github.com/acclectic/media-organizer/issues/28
